apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xkubernetes.lab.example.com
  labels:
    provider: kubernetes-local
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: lab.example.com/v1alpha1
    kind: XKubernetes
  resources:
    - name: kubernetescluster
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: test-namespace
      patches:
        - fromFieldPath: "spec.clusterName"
          toFieldPath: "spec.forProvider.manifest.metadata.name" 